/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Session;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import model.DataBaseManager;
import org.apache.derby.client.am.DateTime;

/**
 *
 * @author ArcadeHitman
 */
public class usermain extends javax.swing.JFrame {
    private Session usession;
    private DataBaseManager db;
    private List< String > meals;
    private Date viewDate;
    private int currentMeal = 0;

    /**
     * Creates new form usermain
     */
    public usermain( String fn, String ln) {
        initComponents();
        displayName.setText("Hello " + fn + " " + ln +".");
        this.usession = Session.getSession();
        this.db = DataBaseManager.getDataBase();
        this.updateDate( new Date() );
        
    }
    
    /**
     * Updates the date field and finds associated meals.
     * 
     * @param nDate The date to show.
     */
    private void updateDate( Date nDate ) {
      this.viewDate = nDate;
      this.lblDate.setText( this.viewDate.toString() );
      this.meals =
          this.db.getMealsForDate(this.usession.getUserName(), this.viewDate );
      System.out.println( this.meals.size() );
      System.out.println( this.meals );
      this.updateMeal( 0 );
    }
    
    /**
     * Updates the meal name field and lists out characteristics such as courses.
     * 
     * @param meal The meal index.
     */
    private void updateMeal( int meal ) {
      int mealCount = this.meals.size();
      if ( mealCount > 0 ) {
        this.currentMeal = ( mealCount + meal ) % mealCount;
        String mealName = this.meals.get( this.currentMeal );
        this.lblMealName.setText( mealName );
        this.lblCourseList.setText(
                this.db.getCoursesForMeal( mealName ).toString() );
        this.lblIngredientList.setText(
                this.db.getIngredientsForMeal( mealName ).toString() );
      }
      else {
        this.lblMealName.setText( "" );
      }
    }
    
    public usermain(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayName = new javax.swing.JLabel();
        btnViewDietaryRecommendation = new javax.swing.JButton();
        btnPreferences = new javax.swing.JButton();
        btnDateBack = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        btnDateForward = new javax.swing.JButton();
        btnMealForward = new javax.swing.JButton();
        lblMealName = new javax.swing.JLabel();
        btnMealBack = new javax.swing.JButton();
        lblNutrition = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblIngredientList = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        jLabel9 = new javax.swing.JLabel();
        lblCourseList = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayName.setText("*First and last name here*");

        btnViewDietaryRecommendation.setText("View Dietary Restrictions");
        btnViewDietaryRecommendation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDietaryRecommendationActionPerformed(evt);
            }
        });

        btnPreferences.setText("View/Edit Preferences");
        btnPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreferencesActionPerformed(evt);
            }
        });

        btnDateBack.setText("<-");
        btnDateBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateBackActionPerformed(evt);
            }
        });

        lblDate.setText("*Date*");

        btnDateForward.setText("->");
        btnDateForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateForwardActionPerformed(evt);
            }
        });

        btnMealForward.setText("->");
        btnMealForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMealForwardActionPerformed(evt);
            }
        });

        lblMealName.setText("*Meal Name*");

        btnMealBack.setText("<-");
        btnMealBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMealBackActionPerformed(evt);
            }
        });

        lblNutrition.setText("*fat, caloris, sodium, etc.*");

        jLabel5.setText("Nutritional Facts:");

        lblIngredientList.setText("*List*");

        jLabel3.setText("Ingredients:");

        jLabel9.setText("Courses:");

        lblCourseList.setText("*List*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDateBack)
                            .addComponent(btnMealBack))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMealName)
                            .addComponent(lblDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDateForward, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMealForward, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 137, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(displayName)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPreferences)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnViewDietaryRecommendation)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIngredientList)
                                    .addComponent(lblNutrition))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblCourseList)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(btnDateBack)
                    .addComponent(btnDateForward))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMealName)
                    .addComponent(btnMealBack)
                    .addComponent(btnMealForward))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCourseList)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIngredientList)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNutrition)
                .addGap(70, 70, 70)
                .addComponent(btnViewDietaryRecommendation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPreferences)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDietaryRecommendationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDietaryRecommendationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewDietaryRecommendationActionPerformed

    private void btnPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreferencesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreferencesActionPerformed

  private void btnMealBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMealBackActionPerformed
    this.updateMeal( this.currentMeal - 1 );
  }//GEN-LAST:event_btnMealBackActionPerformed

  private void btnMealForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMealForwardActionPerformed
    this.updateMeal( this.currentMeal + 1 );
  }//GEN-LAST:event_btnMealForwardActionPerformed

  private void btnDateBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateBackActionPerformed
    Calendar cal = Calendar.getInstance();
    cal.setTime( this.viewDate );
    cal.add( cal.DATE, -1 );
    this.updateDate( cal.getTime() );
  }//GEN-LAST:event_btnDateBackActionPerformed

  private void btnDateForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateForwardActionPerformed
    Calendar cal = Calendar.getInstance();
    cal.setTime( this.viewDate );
    cal.add( cal.DATE, 1 );
    this.updateDate( cal.getTime() );
  }//GEN-LAST:event_btnDateForwardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usermain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usermain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usermain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usermain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usermain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDateBack;
    private javax.swing.JButton btnDateForward;
    private javax.swing.JButton btnMealBack;
    private javax.swing.JButton btnMealForward;
    private javax.swing.JButton btnPreferences;
    private javax.swing.JButton btnViewDietaryRecommendation;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel displayName;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCourseList;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblIngredientList;
    private javax.swing.JLabel lblMealName;
    private javax.swing.JLabel lblNutrition;
    // End of variables declaration//GEN-END:variables
}
