-- Generated by Oracle SQL Developer Data Modeler 3.3.0.747
--   at:        2013-11-14 13:18:02 MST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE
  TABLE Attributes
  (
    NAME          VARCHAR2 (50) ,
    Attributes_ID NUMBER NOT NULL
  ) ;
ALTER TABLE Attributes ADD CONSTRAINT Attributes_PK PRIMARY KEY
(
  Attributes_ID
)
;

CREATE
  TABLE Course
  (
    NAME               VARCHAR2 (50) ,
    SERVINGS           INTEGER ,
    Course_ID          NUMBER NOT NULL ,
    Recipee_Recipee_ID NUMBER
  ) ;
CREATE UNIQUE INDEX Course__IDX ON Course
  (
    Recipee_Recipee_ID ASC
  )
  ;
  ALTER TABLE Course ADD CONSTRAINT Course_PK PRIMARY KEY
  (
    Course_ID
  )
  ;

CREATE
  TABLE DayPlans
  (
    "DATE"         DATE ,
    DayPlans_ID    NUMBER NOT NULL ,
    Users_Users_ID NUMBER NOT NULL
  ) ;
ALTER TABLE DayPlans ADD CONSTRAINT DayPlans_PK PRIMARY KEY
(
  DayPlans_ID
)
;

CREATE
  TABLE Dietition
  (
    User_ID_FK         NUMBER NOT NULL ,
    Prescription_ID_FK NUMBER NOT NULL
  ) ;
ALTER TABLE Dietition ADD CONSTRAINT Dietition_PK PRIMARY KEY
(
  User_ID_FK
)
;

CREATE
  TABLE Emails
  (
    ADDRESS        VARCHAR2 (1000) ,
    Users_Users_ID NUMBER NOT NULL
  ) ;

CREATE
  TABLE Ingredients
  (
    NAME             VARCHAR2 (50) ,
    FAT              INTEGER ,
    CALORIES         INTEGER ,
    Ingredients_ID   NUMBER NOT NULL ,
    Course_Course_ID NUMBER
  ) ;
ALTER TABLE Ingredients ADD CONSTRAINT Ingredients_PK PRIMARY KEY
(
  Ingredients_ID
)
;

CREATE
  TABLE Meals
  (
    NAME                 VARCHAR2 (50) ,
    Meals_ID             NUMBER NOT NULL ,
    DayPlans_DayPlans_ID NUMBER
  ) ;
ALTER TABLE Meals ADD CONSTRAINT Meals_PK PRIMARY KEY
(
  Meals_ID
)
;

CREATE
  TABLE MealsCourses
  (
    Meals_Meals_ID   NUMBER NOT NULL ,
    Course_Course_ID NUMBER NOT NULL
  ) ;
ALTER TABLE MealsCourses ADD CONSTRAINT MealsCourses__IDX PRIMARY KEY
(
  Meals_Meals_ID, Course_Course_ID
)
;

CREATE
  TABLE MealsFoodAttributes
  (
    Meals_Meals_ID           NUMBER NOT NULL ,
    Attributes_Attributes_ID NUMBER NOT NULL
  ) ;
ALTER TABLE MealsFoodAttributes ADD CONSTRAINT MealsFoodAttributes__IDX PRIMARY
KEY
(
  Meals_Meals_ID, Attributes_Attributes_ID
)
;

CREATE
  TABLE Prescription
  (
    "DATE"          DATE ,
    Prescription_ID NUMBER NOT NULL ,
    User_ID_FK      NUMBER NOT NULL
  ) ;
ALTER TABLE Prescription ADD CONSTRAINT Prescription_PK PRIMARY KEY
(
  Prescription_ID
)
;

CREATE
  TABLE PrescriptionAttributes
  (
    Prescription_Prescription_ID NUMBER NOT NULL ,
    Attributes_Attributes_ID     NUMBER NOT NULL
  ) ;
ALTER TABLE PrescriptionAttributes ADD CONSTRAINT PrescriptionAttributes__IDX
PRIMARY KEY
(
  Prescription_Prescription_ID, Attributes_Attributes_ID
)
;

CREATE
  TABLE Ratings
  (
    STARS          INTEGER ,
    Meals_Meals_ID NUMBER NOT NULL ,
    Users_Users_ID NUMBER NOT NULL
  ) ;

CREATE
  TABLE Stores
  (
    NAME                       VARCHAR2 (50) ,
    Ingredients_Ingredients_ID NUMBER NOT NULL ,
    PRICE                      NUMBER (2)
  ) ;

CREATE
  TABLE UserFavoriteMeals
  (
    Users_Users_ID NUMBER NOT NULL ,
    Meals_Meals_ID NUMBER NOT NULL
  ) ;
ALTER TABLE UserFavoriteMeals ADD CONSTRAINT UserFavoriteMeals__IDX PRIMARY KEY
(
  Users_Users_ID, Meals_Meals_ID
)
;

CREATE
  TABLE UserType
  (
    NAME        VARCHAR2 (50) NOT NULL ,
    UserType_ID NUMBER NOT NULL
  ) ;
ALTER TABLE UserType ADD CONSTRAINT UserType_PK PRIMARY KEY
(
  NAME
)
;

CREATE
  TABLE Users
  (
    FNAME    VARCHAR2 (50) ,
    LNAME    VARCHAR2 (50) ,
    UNAME    VARCHAR2 (50) ,
    GENDER   CHAR (1) ,
    PASSWORD VARCHAR2 (200) ,
    Users_ID NUMBER NOT NULL
  ) ;
ALTER TABLE Users ADD CONSTRAINT Users_PK PRIMARY KEY
(
  Users_ID
)
;

ALTER TABLE DayPlans ADD CONSTRAINT DayPlans_Users_FK FOREIGN KEY (
Users_Users_ID ) REFERENCES Users ( Users_ID ) ;

ALTER TABLE Dietition ADD CONSTRAINT Dietition_Prescription_FK FOREIGN KEY (
Prescription_ID_FK ) REFERENCES Prescription ( Prescription_ID ) ;

ALTER TABLE Dietition ADD CONSTRAINT Dietition_Users_FK FOREIGN KEY (
User_ID_FK ) REFERENCES Users ( Users_ID ) ;

-- Error - Foreign Key Dietition_Users_FK has no columns

ALTER TABLE Emails ADD CONSTRAINT Emails_Users_FK FOREIGN KEY ( Users_Users_ID
) REFERENCES Users ( Users_ID ) ;

ALTER TABLE MealsCourses ADD CONSTRAINT FK_ASS_10 FOREIGN KEY ( Meals_Meals_ID
) REFERENCES Meals ( Meals_ID ) ;

ALTER TABLE MealsCourses ADD CONSTRAINT FK_ASS_11 FOREIGN KEY (
Course_Course_ID ) REFERENCES Course ( Course_ID ) ;

ALTER TABLE MealsFoodAttributes ADD CONSTRAINT FK_ASS_12 FOREIGN KEY (
Meals_Meals_ID ) REFERENCES Meals ( Meals_ID ) ;

ALTER TABLE MealsFoodAttributes ADD CONSTRAINT FK_ASS_13 FOREIGN KEY (
Attributes_Attributes_ID ) REFERENCES Attributes ( Attributes_ID ) ;

ALTER TABLE PrescriptionAttributes ADD CONSTRAINT FK_ASS_14 FOREIGN KEY (
Prescription_Prescription_ID ) REFERENCES Prescription ( Prescription_ID ) ;

ALTER TABLE PrescriptionAttributes ADD CONSTRAINT FK_ASS_15 FOREIGN KEY (
Attributes_Attributes_ID ) REFERENCES Attributes ( Attributes_ID ) ;

ALTER TABLE UserFavoriteMeals ADD CONSTRAINT FK_ASS_21 FOREIGN KEY (
Users_Users_ID ) REFERENCES Users ( Users_ID ) ;

ALTER TABLE UserFavoriteMeals ADD CONSTRAINT FK_ASS_22 FOREIGN KEY (
Meals_Meals_ID ) REFERENCES Meals ( Meals_ID ) ;

ALTER TABLE Ingredients ADD CONSTRAINT Ingredients_Course_FK FOREIGN KEY (
Course_Course_ID ) REFERENCES Course ( Course_ID ) ;

ALTER TABLE Meals ADD CONSTRAINT Meals_DayPlans_FK FOREIGN KEY (
DayPlans_DayPlans_ID ) REFERENCES DayPlans ( DayPlans_ID ) ;

-- Error - Foreign Key Prescription_Dietition_FK has no columns

-- Error - Foreign Key Prescription_Users_FK has no columns

ALTER TABLE Prescription ADD CONSTRAINT Prescription_Users_FK FOREIGN KEY (
User_ID_FK ) REFERENCES Users ( Users_ID ) ;

ALTER TABLE Ratings ADD CONSTRAINT Ratings_Meals_FK FOREIGN KEY (
Meals_Meals_ID ) REFERENCES Meals ( Meals_ID ) ;

ALTER TABLE Ratings ADD CONSTRAINT Ratings_Users_FK FOREIGN KEY (
Users_Users_ID ) REFERENCES Users ( Users_ID ) ;

ALTER TABLE Stores ADD CONSTRAINT Stores_Ingredients_FK FOREIGN KEY (
Ingredients_Ingredients_ID ) REFERENCES Ingredients ( Ingredients_ID ) ;

ALTER TABLE UserType ADD CONSTRAINT UserType_Users_FK FOREIGN KEY ( UserType_ID
) REFERENCES Users ( Users_ID ) ;

-- Error - Foreign Key Users_Dietition_FK has no columns

-- Error - Foreign Key Users_Prescription_FK has no columns

-- Error - Foreign Key Users_UserType_FK has no columns

CREATE SEQUENCE Attributes_Attributes_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Attributes_Attributes_ID_TRG BEFORE
  INSERT
    ON Attributes FOR EACH ROW WHEN
    (
      NEW.Attributes_ID IS NULL
    )
    BEGIN
  SELECT
    Attributes_Attributes_ID_SEQ.NEXTVAL
  INTO
    :NEW.Attributes_ID
  FROM
    DUAL;
END;
/

CREATE SEQUENCE Course_Course_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Course_Course_ID_TRG BEFORE
  INSERT
    ON Course FOR EACH ROW WHEN
    (
      NEW.Course_ID IS NULL
    )
    BEGIN
  SELECT
    Course_Course_ID_SEQ.NEXTVAL
  INTO
    :NEW.Course_ID
  FROM
    DUAL;
END;
/

CREATE SEQUENCE DayPlans_DayPlans_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER DayPlans_DayPlans_ID_TRG BEFORE
  INSERT
    ON DayPlans FOR EACH ROW WHEN
    (
      NEW.DayPlans_ID IS NULL
    )
    BEGIN
  SELECT
    DayPlans_DayPlans_ID_SEQ.NEXTVAL
  INTO
    :NEW.DayPlans_ID
  FROM
    DUAL;
END;
/

CREATE SEQUENCE Ingredients_Ingredients_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Ingredients_Ingredients_ID_TRG BEFORE
  INSERT
    ON Ingredients FOR EACH ROW WHEN
    (
      NEW.Ingredients_ID IS NULL
    )
    BEGIN
  SELECT
    Ingredients_Ingredients_ID_SEQ.NEXTVAL
  INTO
    :NEW.Ingredients_ID
  FROM
    DUAL;
END;
/

CREATE SEQUENCE Meals_Meals_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Meals_Meals_ID_TRG BEFORE
  INSERT
    ON Meals FOR EACH ROW WHEN
    (
      NEW.Meals_ID IS NULL
    )
    BEGIN
  SELECT
    Meals_Meals_ID_SEQ.NEXTVAL
  INTO
    :NEW.Meals_ID
  FROM
    DUAL;
END;
/

CREATE SEQUENCE Prescription_Prescription_ID START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Prescription_Prescription_ID BEFORE
  INSERT
    ON Prescription FOR EACH ROW WHEN
    (
      NEW.Prescription_ID IS NULL
    )
    BEGIN
  SELECT
    Prescription_Prescription_ID.NEXTVAL
  INTO
    :NEW.Prescription_ID
  FROM
    DUAL;
END;
/

CREATE SEQUENCE UserType_UserType_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER UserType_UserType_ID_TRG BEFORE
  INSERT
    ON UserType FOR EACH ROW WHEN
    (
      NEW.UserType_ID IS NULL
    )
    BEGIN
  SELECT
    UserType_UserType_ID_SEQ.NEXTVAL
  INTO
    :NEW.UserType_ID
  FROM
    DUAL;
END;
/

CREATE SEQUENCE Users_Users_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Users_Users_ID_TRG BEFORE
  INSERT
    ON Users FOR EACH ROW WHEN
    (
      NEW.Users_ID IS NULL
    )
    BEGIN
  SELECT
    Users_Users_ID_SEQ.NEXTVAL
  INTO
    :NEW.Users_ID
  FROM
    DUAL;
END;
/


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             1
-- ALTER TABLE                             32
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           8
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          8
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   6
-- WARNINGS                                 0
