    DROP CONSTRAINT DayPlans_Users_FK ;
--
--
    DROP CONSTRAINT Dietition_Prescription_FK ;
--
--
    DROP CONSTRAINT Dietition_Users_FK ;
--
--
    DROP CONSTRAINT Emails_Users_FK ;
--
--
    DROP CONSTRAINT FK_ASS_10 ;
--
--
    DROP CONSTRAINT FK_ASS_11 ;
--
--
    DROP CONSTRAINT FK_ASS_12 ;
--
--
    DROP CONSTRAINT FK_ASS_13 ;
--
--
    DROP CONSTRAINT FK_ASS_14 ;
--
--
    DROP CONSTRAINT FK_ASS_15 ;
--
--
    DROP CONSTRAINT FK_ASS_21 ;
--
--
    DROP CONSTRAINT FK_ASS_22 ;
--
--
    DROP CONSTRAINT Ingredients_Course_FK ;
--
--
    DROP CONSTRAINT Meals_DayPlans_FK ;
--
--
    DROP CONSTRAINT Prescription_Users_FK ;
--
--
    DROP CONSTRAINT Ratings_Meals_FK ;
--
--
    DROP CONSTRAINT Ratings_Users_FK ;
--
--
    DROP CONSTRAINT Stores_Ingredients_FK ;
--
--
    DROP CONSTRAINT UserType_Users_FK ;
-- Generated by Oracle SQL Developer Data Modeler 3.1.0.691
--
DROP TABLE Attributes;
--
DROP TABLE Course;
--
DROP TABLE DayPlans;
--
DROP TABLE Dietition;
--
DROP TABLE Emails;
--
DROP TABLE Ingredients;
--
DROP TABLE Meals;
--
DROP TABLE MealsCourses;
--
DROP TABLE MealsFoodAttributes;
--
DROP TABLE Prescription;
--
DROP TABLE PrescriptionAttributes;
--
DROP TABLE Ratings;
--
DROP TABLE Stores;
--
DROP TABLE UserFavoriteMeals;
--
DROP TABLE UserType;
--
DROP TABLE Users;
--
DROP SEQUENCE Attributes;
--
DROP SEQUENCE Course;
--
DROP SEQUENCE DayPlans;
--
DROP SEQUENCE Ingredients;
--
DROP SEQUENCE Meals;
--
DROP SEQUENCE Prescription;
--
DROP SEQUENCE UserType;
--
DROP SEQUENCE Users;
--
-- DROP TABLE ;
--
-- DROP SEQUENCE ;
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
ALTER TABLE Course DROP CONSTRAINT Course_Recipee_FK ;
ALTER TABLE DayPlans DROP CONSTRAINT DayPlans_Users_FK ;
ALTER TABLE DietaryPrescription DROP CONSTRAINT DietaryPrescription_Dietitian_FK ;
ALTER TABLE DietaryPrescription DROP CONSTRAINT DietaryPrescription_Users_FK ;
ALTER TABLE Dietitian DROP CONSTRAINT Dietitian_Users_FK ;
ALTER TABLE Emails DROP CONSTRAINT Emails_Users_FK ;
ALTER TABLE MealsCourses DROP CONSTRAINT FK_ASS_12 ;
ALTER TABLE MealsCourses DROP CONSTRAINT FK_ASS_13 ;
ALTER TABLE MealsFoodAttributes DROP CONSTRAINT FK_ASS_14 ;
ALTER TABLE MealsFoodAttributes DROP CONSTRAINT FK_ASS_15 ;
ALTER TABLE DoctorRecommendationAttributes DROP CONSTRAINT FK_ASS_6 ;
ALTER TABLE DoctorRecommendationAttributes DROP CONSTRAINT FK_ASS_7 ;
ALTER TABLE Ingredients DROP CONSTRAINT Ingredients_Course_FK ;
ALTER TABLE Meals DROP CONSTRAINT Meals_DayPlans_FK ;
ALTER TABLE Meals DROP CONSTRAINT Meals_Users_FK ;
ALTER TABLE Ratings DROP CONSTRAINT Ratings_Meals_FK ;
ALTER TABLE Ratings DROP CONSTRAINT Ratings_Users_FK ;
ALTER TABLE Recipee DROP CONSTRAINT Recipee_Course_FK ;
ALTER TABLE Steps DROP CONSTRAINT Steps_Recipee_FK ;
ALTER TABLE Stores DROP CONSTRAINT Stores_Ingredients_FK ;
ALTER TABLE Users DROP CONSTRAINT Users_DietaryPrescription_FK ;
ALTER TABLE Users DROP CONSTRAINT Users_Dietitian_FK ;
ALTER TABLE Users DROP CONSTRAINT Users_UserType_FK ;
-- Generated by Oracle SQL Developer Data Modeler 3.3.0.747
--
DROP TABLE Attributes;
--
DROP TABLE Course;
--
DROP TABLE DayPlans;
--
DROP TABLE DietaryPrescription;
--
DROP TABLE Dietitian;
--
DROP TABLE DoctorRecommendationAttributes;
--
DROP TABLE Emails;
--
DROP TABLE Ingredients;
--
DROP TABLE Meals;
--
DROP TABLE MealsCourses;
--
DROP TABLE MealsFoodAttributes;
--
DROP TABLE Ratings;
--
DROP TABLE Recipee;
--
DROP TABLE Steps;
--
DROP TABLE Stores;
--
DROP TABLE UserType;
--
DROP TABLE Users;
--
DROP SEQUENCE Attributes;
--
DROP SEQUENCE Course;
--
DROP SEQUENCE DayPlans;
--
DROP SEQUENCE DietaryPrescription;
--
DROP SEQUENCE Dietitian;
--
DROP SEQUENCE Ingredients;
--
DROP SEQUENCE Meals;
--
DROP SEQUENCE Recipee;
--
DROP SEQUENCE UserType;
--
DROP SEQUENCE Users;
