-- Generated by Oracle SQL Developer Data Modeler 3.1.0.691
--   at:        2013-11-19 21:54:25 MST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE Attributes;
CREATE TABLE Attributes 
    ( 
     ATTRIBUTES_ID_PK NUMBER  NOT NULL , 
     NAME VARCHAR2 (50) 
    ) 
;



DROP TABLE Course;
CREATE TABLE Course 
    ( 
     COURSE_ID_PK NUMBER  NOT NULL , 
     NAME VARCHAR2 (50) , 
     SERVINGS INTEGER
    ) 
;



DROP TABLE DayPlans;
CREATE TABLE DayPlans 
    ( 
     "DATE" DATE ,
     USERS_ID NUMBER  NOT NULL 
    ) 
;



DROP TABLE Dietition;
CREATE TABLE Dietition 
    ( 
     USER_ID NUMBER  NOT NULL , 
     PRESCRIPTION_ID NUMBER  NOT NULL 
    ) 
;


DROP TABLE Emails;
CREATE TABLE Emails 
    ( 
     ADDRESS VARCHAR2 (1000) , 
     USERS_ID NUMBER  NOT NULL 
    ) 
;




DROP TABLE Ingredients;
CREATE TABLE Ingredients 
    (
     INGREDIENTS_ID_PK NUMBER  NOT NULL , 
     NAME VARCHAR2 (50) , 
     FAT INTEGER , 
     CALORIES INTEGER,
     COURSE_ID NUMBER 
    ) 
;



DROP TABLE Meals;
CREATE TABLE Meals 
    ( 
     MEALS_ID_PK NUMBER  NOT NULL , 
     NAME VARCHAR2 (50) , 
     DAYPLANS_ID NUMBER 
    ) 
;




DROP TABLE MealsCourses;
CREATE TABLE MealsCourses 
    ( 
     MEALS_ID NUMBER  NOT NULL , 
     COURSE_ID NUMBER  NOT NULL 
    ) 
;




DROP TABLE MealsFoodAttributes;
CREATE TABLE MealsFoodAttributes 
    ( 
     MEALS_ID NUMBER  NOT NULL , 
     ATTRIBUTES_ID NUMBER  NOT NULL 
    ) 
;




DROP TABLE Prescription;
CREATE TABLE Prescription 
    ( 
     PRESCIPTION_ID_PK NUMBER  NOT NULL , 
     "DATE" DATE , 
     USER_ID NUMBER  NOT NULL 
    ) 
;




DROP TABLE PrescriptionAttributes;
CREATE TABLE PrescriptionAttributes 
    ( 
     PRESCRIPTION_ID NUMBER  NOT NULL , 
     ATTRIBUTES_ID NUMBER  NOT NULL 
    ) 
;




DROP TABLE Ratings;
CREATE TABLE Ratings 
    ( 
     MEALS_ID NUMBER  NOT NULL , 
     USERS_ID NUMBER  NOT NULL , 
     STARS INTEGER 
    ) 
;



DROP TABLE UserType;
CREATE TABLE UserType 
    (
     USER_TYPE_ID_PK NUMBER  NOT NULL 
     ,
     NAME VARCHAR2 (50)  NOT NULL
    ) 
;


DROP TABLE Users;
CREATE TABLE Users 
    ( 
     USERS_ID_PK NUMBER  NOT NULL , 
     FNAME VARCHAR2 (50) , 
     LNAME VARCHAR2 (50) , 
     UNAME VARCHAR2 (50) , 
     GENDER CHAR (1) , 
     PASSWORD VARCHAR2 (200),
     USER_TYPE_ID NUMBER  NOT NULL 
    ) 
;