ALTER TABLE Course DROP CONSTRAINT Course_Recipee_FK ;
ALTER TABLE DayPlans DROP CONSTRAINT DayPlans_Users_FK ;
ALTER TABLE DietaryPrescription DROP CONSTRAINT DietaryPrescription_Dietitian_FK ;
ALTER TABLE DietaryPrescription DROP CONSTRAINT DietaryPrescription_Users_FK ;
ALTER TABLE Dietitian DROP CONSTRAINT Dietitian_Users_FK ;
ALTER TABLE Emails DROP CONSTRAINT Emails_Users_FK ;
ALTER TABLE MealsCourses DROP CONSTRAINT FK_ASS_12 ;
ALTER TABLE MealsCourses DROP CONSTRAINT FK_ASS_13 ;
ALTER TABLE MealsFoodAttributes DROP CONSTRAINT FK_ASS_14 ;
ALTER TABLE MealsFoodAttributes DROP CONSTRAINT FK_ASS_15 ;
ALTER TABLE DoctorRecommendationAttributes DROP CONSTRAINT FK_ASS_6 ;
ALTER TABLE DoctorRecommendationAttributes DROP CONSTRAINT FK_ASS_7 ;
ALTER TABLE Ingredients DROP CONSTRAINT Ingredients_Course_FK ;
ALTER TABLE Meals DROP CONSTRAINT Meals_DayPlans_FK ;
ALTER TABLE Meals DROP CONSTRAINT Meals_Users_FK ;
ALTER TABLE Ratings DROP CONSTRAINT Ratings_Meals_FK ;
ALTER TABLE Ratings DROP CONSTRAINT Ratings_Users_FK ;
ALTER TABLE Recipee DROP CONSTRAINT Recipee_Course_FK ;
ALTER TABLE Steps DROP CONSTRAINT Steps_Recipee_FK ;
ALTER TABLE Stores DROP CONSTRAINT Stores_Ingredients_FK ;
ALTER TABLE Users DROP CONSTRAINT Users_DietaryPrescription_FK ;
ALTER TABLE Users DROP CONSTRAINT Users_Dietitian_FK ;
ALTER TABLE Users DROP CONSTRAINT Users_UserType_FK ;
-- Generated by Oracle SQL Developer Data Modeler 3.3.0.747
--   at:        2013-11-13 10:03:04 MST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




DROP TABLE Attributes;
CREATE TABLE Attributes
  (
    NAME VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    Attributes_ID NUMBER NOT NULL
  ) ;
ALTER TABLE Attributes ADD CONSTRAINT Attributes_PK PRIMARY KEY
(
  Attributes_ID
)
;

DROP TABLE Course;
CREATE TABLE Course
  (
    NAME VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    SERVINGS VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    Course_ID          NUMBER NOT NULL ,
    Recipee_Recipee_ID NUMBER
  ) ;
CREATE UNIQUE INDEX Course__IDX ON Course
  (
    Recipee_Recipee_ID ASC
  )
  ;
  ALTER TABLE Course ADD CONSTRAINT Course_PK PRIMARY KEY
  (
    Course_ID
  )
  ;

DROP TABLE DayPlans;
CREATE TABLE DayPlans
  (
    "DATE" VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    DayPlans_ID    NUMBER NOT NULL ,
    Users_Users_ID NUMBER NOT NULL
  ) ;
ALTER TABLE DayPlans ADD CONSTRAINT DayPlans_PK PRIMARY KEY
(
  DayPlans_ID
)
;

DROP TABLE DietaryPrescription;
CREATE TABLE DietaryPrescription
  (
    "DATE" VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    DietaryPrescription_ID NUMBER NOT NULL ,
    DD_ID NUMBER NOT NULL ,
    Users_Users_ID         NUMBER
  ) ;
CREATE UNIQUE INDEX DietaryPrescription__IDX ON DietaryPrescription
  (
    Users_Users_ID ASC
  )
  ;
  ALTER TABLE DietaryPrescription ADD CONSTRAINT DietaryPrescription_PK PRIMARY KEY
  (
    DietaryPrescription_ID
  )
  ;

DROP TABLE Dietitian;
CREATE TABLE Dietitian
  (
    Dietitian_ID   NUMBER NOT NULL ,
    Users_Users_ID NUMBER
  ) ;
CREATE UNIQUE INDEX Dietitian__IDX ON Dietitian
  (
    Users_Users_ID ASC
  )
  ;
  ALTER TABLE Dietitian ADD CONSTRAINT Dietitian_PK PRIMARY KEY
  (
    Dietitian_ID
  )
  ;

DROP TABLE DoctorRecommendationAttributes;
CREATE TABLE DoctorRecommendationAttributes
  (
    --  ERROR: Column name length exceeds maximum allowed length(30)
    DP_ID NUMBER NOT NULL ,
    Attributes_Attributes_ID                   NUMBER NOT NULL
  ) ;
--  ERROR: PK name length exceeds maximum allowed length(30)
ALTER TABLE DoctorRecommendationAttributes ADD CONSTRAINT DoctorRecommendationAttributes__IDX PRIMARY KEY
(
  DP_ID, Attributes_Attributes_ID
)
;

DROP TABLE Emails;
CREATE TABLE Emails
  (
    ADDRESS VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    Users_Users_ID NUMBER NOT NULL
  ) ;

DROP TABLE Ingredients;
CREATE TABLE Ingredients
  (
    NAME VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    FAT VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    CALORIES VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    Ingredients_ID   NUMBER NOT NULL ,
    Course_Course_ID NUMBER
  ) ;
ALTER TABLE Ingredients ADD CONSTRAINT Ingredients_PK PRIMARY KEY
(
  Ingredients_ID
)
;

DROP TABLE Meals;
CREATE TABLE Meals
  (
    NAME VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    Meals_ID             NUMBER NOT NULL ,
    DayPlans_DayPlans_ID NUMBER ,
    Users_Users_ID       NUMBER NOT NULL
  ) ;
ALTER TABLE Meals ADD CONSTRAINT Meals_PK PRIMARY KEY
(
  Meals_ID
)
;

DROP TABLE MealsCourses;
CREATE TABLE MealsCourses
  (
    Meals_Meals_ID   NUMBER NOT NULL ,
    Course_Course_ID NUMBER NOT NULL
  ) ;
ALTER TABLE MealsCourses ADD CONSTRAINT MealsCourses__IDX PRIMARY KEY
(
  Meals_Meals_ID, Course_Course_ID
)
;

DROP TABLE MealsFoodAttributes;
CREATE TABLE MealsFoodAttributes
  (
    Meals_Meals_ID           NUMBER NOT NULL ,
    Attributes_Attributes_ID NUMBER NOT NULL
  ) ;
ALTER TABLE MealsFoodAttributes ADD CONSTRAINT MealsFoodAttributes__IDX PRIMARY KEY
(
  Meals_Meals_ID, Attributes_Attributes_ID
)
;

DROP TABLE Ratings;
CREATE TABLE Ratings
  (
    STARS VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    Meals_Meals_ID NUMBER NOT NULL ,
    Users_Users_ID NUMBER NOT NULL
  ) ;

DROP TABLE Recipee;
CREATE TABLE Recipee
  (
    NAME VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    Recipee_ID       NUMBER NOT NULL ,
    Course_Course_ID NUMBER
  ) ;
CREATE UNIQUE INDEX Recipee__IDX ON Recipee
  (
    Course_Course_ID ASC
  )
  ;
  ALTER TABLE Recipee ADD CONSTRAINT Recipee_PK PRIMARY KEY
  (
    Recipee_ID
  )
  ;

DROP TABLE Steps;
CREATE TABLE Steps
  (
    TEXT VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    Recipee_Recipee_ID NUMBER NOT NULL
  ) ;

DROP TABLE Stores;
CREATE TABLE Stores
  (
    NAME VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    Ingredients_Ingredients_ID NUMBER NOT NULL ,
    PRICE VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
  ) ;

DROP TABLE UserType;
CREATE TABLE UserType
  (
    NAME VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    UserType_ID NUMBER NOT NULL
  ) ;
ALTER TABLE UserType ADD CONSTRAINT UserType_PK PRIMARY KEY
(
  UserType_ID
)
;

DROP TABLE Users;
CREATE TABLE Users
  (
    FNAME VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    LNAME VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    UNAME VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    GENDER VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    PASSWORD VARCHAR(20)
    --  ERROR: Datatype VARCHAR(20) is not allowed
    ,
    Users_ID               NUMBER NOT NULL ,
    DD_ID NUMBER ,
    --  ERROR: Column name length exceeds maximum allowed length(30)
    DPDP_ID NUMBER ,
    UserType_UserType_ID                       NUMBER
  ) ;
CREATE UNIQUE INDEX Users__IDX ON Users
  (
    DD_ID ASC
  )
  ;
CREATE UNIQUE INDEX Users__IDXv1 ON Users
  (
    DPDP_ID ASC
  )
  ;
  ALTER TABLE Users ADD CONSTRAINT Users_PK PRIMARY KEY
  (
    Users_ID
  )
  ;

ALTER TABLE Course ADD CONSTRAINT Course_Recipee_FK FOREIGN KEY ( Recipee_Recipee_ID ) REFERENCES Recipee ( Recipee_ID ) ;

ALTER TABLE DayPlans ADD CONSTRAINT DayPlans_Users_FK FOREIGN KEY ( Users_Users_ID ) REFERENCES Users ( Users_ID ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE DietaryPrescription ADD CONSTRAINT DietaryPrescription_Dietitian_FK FOREIGN KEY ( DD_ID ) REFERENCES Dietitian ( Dietitian_ID ) ;

ALTER TABLE DietaryPrescription ADD CONSTRAINT DietaryPrescription_Users_FK FOREIGN KEY ( Users_Users_ID ) REFERENCES Users ( Users_ID ) ;

ALTER TABLE Dietitian ADD CONSTRAINT Dietitian_Users_FK FOREIGN KEY ( Users_Users_ID ) REFERENCES Users ( Users_ID ) ;

ALTER TABLE Emails ADD CONSTRAINT Emails_Users_FK FOREIGN KEY ( Users_Users_ID ) REFERENCES Users ( Users_ID ) ;

ALTER TABLE MealsCourses ADD CONSTRAINT FK_ASS_12 FOREIGN KEY ( Meals_Meals_ID ) REFERENCES Meals ( Meals_ID ) ;

ALTER TABLE MealsCourses ADD CONSTRAINT FK_ASS_13 FOREIGN KEY ( Course_Course_ID ) REFERENCES Course ( Course_ID ) ;

ALTER TABLE MealsFoodAttributes ADD CONSTRAINT FK_ASS_14 FOREIGN KEY ( Meals_Meals_ID ) REFERENCES Meals ( Meals_ID ) ;

ALTER TABLE MealsFoodAttributes ADD CONSTRAINT FK_ASS_15 FOREIGN KEY ( Attributes_Attributes_ID ) REFERENCES Attributes ( Attributes_ID ) ;

ALTER TABLE DoctorRecommendationAttributes ADD CONSTRAINT FK_ASS_6 FOREIGN KEY ( DPDP_ID ) REFERENCES DietaryPrescription ( DietaryPrescription_ID ) ;

ALTER TABLE DoctorRecommendationAttributes ADD CONSTRAINT FK_ASS_7 FOREIGN KEY ( Attributes_Attributes_ID ) REFERENCES Attributes ( Attributes_ID ) ;

ALTER TABLE Ingredients ADD CONSTRAINT Ingredients_Course_FK FOREIGN KEY ( Course_Course_ID ) REFERENCES Course ( Course_ID ) ;

ALTER TABLE Meals ADD CONSTRAINT Meals_DayPlans_FK FOREIGN KEY ( DayPlans_DayPlans_ID ) REFERENCES DayPlans ( DayPlans_ID ) ;

ALTER TABLE Meals ADD CONSTRAINT Meals_Users_FK FOREIGN KEY ( Users_Users_ID ) REFERENCES Users ( Users_ID ) ;

ALTER TABLE Ratings ADD CONSTRAINT Ratings_Meals_FK FOREIGN KEY ( Meals_Meals_ID ) REFERENCES Meals ( Meals_ID ) ;

ALTER TABLE Ratings ADD CONSTRAINT Ratings_Users_FK FOREIGN KEY ( Users_Users_ID ) REFERENCES Users ( Users_ID ) ;

ALTER TABLE Recipee ADD CONSTRAINT Recipee_Course_FK FOREIGN KEY ( Course_Course_ID ) REFERENCES Course ( Course_ID ) ;

ALTER TABLE Steps ADD CONSTRAINT Steps_Recipee_FK FOREIGN KEY ( Recipee_Recipee_ID ) REFERENCES Recipee ( Recipee_ID ) ;

ALTER TABLE Stores ADD CONSTRAINT Stores_Ingredients_FK FOREIGN KEY ( Ingredients_Ingredients_ID ) REFERENCES Ingredients ( Ingredients_ID ) ;

ALTER TABLE Users ADD CONSTRAINT Users_DietaryPrescription_FK FOREIGN KEY ( DPDP_ID ) REFERENCES DietaryPrescription ( DietaryPrescription_ID ) ;

ALTER TABLE Users ADD CONSTRAINT Users_Dietitian_FK FOREIGN KEY ( DD_ID ) REFERENCES Dietitian ( Dietitian_ID ) ;

ALTER TABLE Users ADD CONSTRAINT Users_UserType_FK FOREIGN KEY ( UserType_UserType_ID ) REFERENCES UserType ( UserType_ID ) ;

DROP SEQUENCE Attributes;
CREATE SEQUENCE Attributes_Attributes_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Attributes_Attributes_ID_TRG BEFORE
  INSERT ON Attributes FOR EACH ROW WHEN (NEW.Attributes_ID IS NULL) BEGIN
  SELECT Attributes_Attributes_ID_SEQ.NEXTVAL INTO :NEW.Attributes_ID FROM DUAL;
END;
/

DROP SEQUENCE Course;
CREATE SEQUENCE Course_Course_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Course_Course_ID_TRG BEFORE
  INSERT ON Course FOR EACH ROW WHEN (NEW.Course_ID IS NULL) BEGIN
  SELECT Course_Course_ID_SEQ.NEXTVAL INTO :NEW.Course_ID FROM DUAL;
END;
/

DROP SEQUENCE DayPlans;
CREATE SEQUENCE DayPlans_DayPlans_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER DayPlans_DayPlans_ID_TRG BEFORE
  INSERT ON DayPlans FOR EACH ROW WHEN (NEW.DayPlans_ID IS NULL) BEGIN
  SELECT DayPlans_DayPlans_ID_SEQ.NEXTVAL INTO :NEW.DayPlans_ID FROM DUAL;
END;
/

DROP SEQUENCE DietaryPrescription;
CREATE SEQUENCE DietaryPrescription_DietaryPre START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER DietaryPrescription_DietaryPre BEFORE
  INSERT ON DietaryPrescription FOR EACH ROW WHEN (NEW.DietaryPrescription_ID IS NULL) BEGIN
  SELECT DietaryPrescription_DietaryPre.NEXTVAL
  INTO :NEW.DietaryPrescription_ID
  FROM DUAL;
END;
/

DROP SEQUENCE Dietitian;
CREATE SEQUENCE DD_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER DD_ID_TRG BEFORE
  INSERT ON Dietitian FOR EACH ROW WHEN (NEW.Dietitian_ID IS NULL) BEGIN
  SELECT DD_ID_SEQ.NEXTVAL INTO :NEW.Dietitian_ID FROM DUAL;
END;
/

DROP SEQUENCE Ingredients;
CREATE SEQUENCE Ingredients_Ingredients_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Ingredients_Ingredients_ID_TRG BEFORE
  INSERT ON Ingredients FOR EACH ROW WHEN (NEW.Ingredients_ID IS NULL) BEGIN
  SELECT Ingredients_Ingredients_ID_SEQ.NEXTVAL
  INTO :NEW.Ingredients_ID
  FROM DUAL;
END;
/

DROP SEQUENCE Meals;
CREATE SEQUENCE Meals_Meals_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Meals_Meals_ID_TRG BEFORE
  INSERT ON Meals FOR EACH ROW WHEN (NEW.Meals_ID IS NULL) BEGIN
  SELECT Meals_Meals_ID_SEQ.NEXTVAL INTO :NEW.Meals_ID FROM DUAL;
END;
/

DROP SEQUENCE Recipee;
CREATE SEQUENCE Recipee_Recipee_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Recipee_Recipee_ID_TRG BEFORE
  INSERT ON Recipee FOR EACH ROW WHEN (NEW.Recipee_ID IS NULL) BEGIN
  SELECT Recipee_Recipee_ID_SEQ.NEXTVAL INTO :NEW.Recipee_ID FROM DUAL;
END;
/

DROP SEQUENCE UserType;
CREATE SEQUENCE UserType_UserType_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER UserType_UserType_ID_TRG BEFORE
  INSERT ON UserType FOR EACH ROW WHEN (NEW.UserType_ID IS NULL) BEGIN
  SELECT UserType_UserType_ID_SEQ.NEXTVAL INTO :NEW.UserType_ID FROM DUAL;
END;
/

DROP SEQUENCE Users;
CREATE SEQUENCE Users_Users_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Users_Users_ID_TRG BEFORE
  INSERT ON Users FOR EACH ROW WHEN (NEW.Users_ID IS NULL) BEGIN
  SELECT Users_Users_ID_SEQ.NEXTVAL INTO :NEW.Users_ID FROM DUAL;
END;
/


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- DROP TABLE ;
CREATE TABLE                            17
-- CREATE INDEX                             6
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          10
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- DROP SEQUENCE ;
--CREATE SEQUENCE                         10
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                  25
-- WARNINGS                                 0
